### ISSUE TITLE
Add examples to the repo

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [simoninireland/epyc#10]
This is an issue created as part of [epyc's JOSS review](https://github.com/openjournals/joss-reviews/issues/3764).

While the online documentation has tutorials that are very well done, I think it would greatly help future users to have an example folder where these tutorials (or similar ones) can be found. In this way the user can immediately start tinkering with the code. 

Note that the `doc/epyc.ipynb` notebook, which is a great resource, requires jupyter (which is not required by the package) and there are no instructions about to launch it, or at least I couldn't find them.

**Comment by simoninireland** [comment]
Great idea about including examples, I'll move them over from the cookbook etc.

The Jupyter notebook needs a small update, and I didn't want to make it too integral to epyc overall, which is why there's no import of jupyter. On the other hand, we do include all the rest of Jupyter, so maybe there's no reason not to.

**Comment by lorenzo-rovigatti** [comment]
The example you added to the `dev` branch does not work on neither branch. I attach here the traceback:

```
Traceback (most recent call last):
  File "first.py", line 64, in <module>
    lab.runExperiment(CurveExperiment())
  File "/home/lorenzo/.local/lib/python3.8/site-packages/epyc/lab.py", line 205, in runExperiment
    nb.addResult(res)
  File "/home/lorenzo/.local/lib/python3.8/site-packages/epyc/labnotebook.py", line 506, in addResult
    self._addResult(results, tag)
  File "/home/lorenzo/.local/lib/python3.8/site-packages/epyc/labnotebook.py", line 470, in _addResult
    rs.addSingleResult(result)
  File "/home/lorenzo/.local/lib/python3.8/site-packages/epyc/resultset.py", line 687, in addSingleResult
    dt = self.inferDtype(rc)
  File "/home/lorenzo/.local/lib/python3.8/site-packages/epyc/resultset.py", line 553, in inferDtype
    self._results = DataFrame(columns=types.keys())
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 411, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/usr/lib/python3/dist-packages/pandas/core/internals/construction.py", line 242, in init_dict
    val = construct_1d_arraylike_from_scalar(np.nan, len(index), nan_dtype)
  File "/usr/lib/python3/dist-packages/pandas/core/dtypes/cast.py", line 1229, in construct_1d_arraylike_from_scalar
    dtype = dtype.dtype
AttributeError: type object 'object' has no attribute 'dtype'
```

**Comment by simoninireland** [comment]
Fixed (I think) -- and I took the opportunity to update the matplotlib code to the new 3d interface as well
